kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gentle
nodes:
  - role: control-plane
    image: kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true,hanko.io/plan=free,hanko.io/hanko-plan=free"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
        listenAddress: "127.0.0.1"
      - containerPort: 443
        hostPort: 443
        protocol: TCP
        listenAddress: "127.0.0.1"
      - containerPort: 53
        hostPort: 53
        protocol: UDP
        listenAddress: "127.0.0.1"
      - containerPort: 5432
        hostPort: 5432
        protocol: TCP
        listenAddress: "127.0.0.1"