grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: true
      maxLines: 1000
promtail:
  enabled: true
loki:
  enabled: true
  isDefault: false
  serviceMonitor:
    enabled: true
    additionalLabels:
      app.kubernetes.io/part-of: kube-prometheus-stack
  config:
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: true
      retention_period: 12h