name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
    steps:
    - uses: actions/checkout@v3
    - name: Install required target
      run: rustup target add ${{ matrix.target }}
    - name: aarch64-specific items
      run: |
        # Settings taken from: https://github.com/rust-lang/rustup/blob/master/.github/workflows/macos-builds-on-all.yaml
        # Use nightly for now
        rustup toolchain install --profile=minimal nightly
        rustup default nightly
      if: matrix.target == 'aarch64-apple-darwin'
    - name: Build
      run: cargo build --verbose --release --target=${{ matrix.target }}
    - name: Run tests
      run: cargo test --verbose
    - name: create artifact folder
      run: mkdir artifact
    - name: Copy yamls
      run: cp -r infra artifacts/infra
    - name: Copy binary
      run: cp ./target/${{ matrix.target }}/release/gentle artifacts/gentle
    - name: Artifact upload
      uses: actions/upload-artifact@v3
      with:
        name: gentle-${{ matrix.target }}
        path: artifacts
