name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin

    steps:
    - uses: actions/checkout@v3
    - name: Install required target
      run: rustup target add ${{ matrix.target }}
    - name: Build
      run: cargo build --verbose --release --target=${{ matrix.target }}
    - name: Run tests
      run: cargo test --verbose
    - name: Artifact upload
      uses: actions/upload-artifact@v3
      with:
        name: Build MacOS
        path: ./target/${{ matrix.target }}/release/gentle
